name: Docker

on:
  push:
    branches: [main]

jobs:
  build-module:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REPO_OWNER }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: ghcr.io/socfortress/copilot-ai-module:latest
          build-args: |
            CRYPTOLENS_KEY=${{ secrets.CRYPTOLENS_KEY }}
            CRYPTOLENS_PRODUCT_ID=${{ secrets.CRYPTOLENS_PRODUCT_ID }}
